version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://db:3306/productdb
      - DATABASE_USERNAME=${DB_USERNAME:-mindful}
      - DATABASE_PASSWORD=${DB_PASSWORD:-mindful2025}
      - JWT_SECRET=${JWT_SECRET:-your-secure-jwt-secret-key}
      - DB_POOL_SIZE=30
      - DB_POOL_MIN_IDLE=10
      - JAVA_OPTS=-Xms512m -Xmx2g -XX:+UseG1GC
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/application.log
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 60s
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=productdb
      - MYSQL_USER=${DB_USERNAME:-mindful}
      - MYSQL_PASSWORD=${DB_PASSWORD:-mindful2025}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d/mysql.conf:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  app-network:
    driver: bridge