# Production configuration with environment variables
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024
  http2:
    enabled: true
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/productdb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:mindful}
    password: ${DATABASE_PASSWORD:mindful2025}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:30}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      pool-name: HikariPool-ProductApp
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.caffeine.CaffeineCacheRegionFactory
  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=30m,expireAfterAccess=15m,recordStats
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

# Production JWT secret from environment
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Optimized logging for production
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.productapp: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.springframework.boot.actuate: WARN
    io.micrometer: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/application.log}
    max-size: 100MB
    max-history: 30